name: Toffee Playlist Auto Updater

on:


  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Checkout Private Repository
        uses: actions/checkout@v4
        with:
          repository: srhady/axsportspvt
          token: ${{ secrets.PAT_TOKEN }}
          path: private_script_dir

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Move Script to Root
        run: |
          cp private_script_dir/toffee_extractor.py .
          rm -rf private_script_dir

      - name: Run Toffee Extractor Script
        run: python toffee_extractor.py

      - name: Commit and Push Changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add toffee_playlist.json toffee_playlist.m3u
          git commit -m "Auto Update Toffee Playlist" || exit 0
          git push
